<?php 
/**
 * This module will disable Credit Transactions for Clients.
 */

 /**
  * Parse and return Email List.
  * @param path_to_file
  * @throws Exception
  * @return array
  */
function parse_suppressed_clients_email_list(string $path_to_file): array {
    if(file_exists($path_to_file)) {
        $json_data = file_get_contents($path_to_file);
        $email_list = json_decode($json_data, true, flags: JSON_THROW_ON_ERROR);
        foreach($email_list as $email) echo '\''. $email['email_address'].'\',<br>';
        return $email_list;
    }
    throw new Exception('Invalid Suppressed Client Email List');
}

// Emails List
define('SUPPRESSED_EMAIL_LIST', [
    'sukhdeepgil2010@hotmail.com',
    'david.traction@shaw.ca',
    'kylearstonge469@gmail.com',
    'dale.morgan@penske.com',
    'sahibhullar751@gmail.com',
    'hdtrcuking1@gmail.com',
    'uniquetrucking.baley@gmail.com',
    'randi@bradleigh.ca',
    'info@capitalcitytruckline.ca',
    'inderjithayre921@gmail.com',
    'frederick@car-fre.com',
    'gerry.tigelaar@pepsico.com',
    'info@dieseldetective.ca',
    'bhadhurnatt@hotmail.com',
    'opjit@hotmail.com',
    'heavysquard98@gmail.com',
    'accounting@transmax.canada.com',
    'surinderpalkehar@gmail.com',
    'ethiocanatrucking@hotmail.com',
    'BESTIMAGETRANSPORT@GMAIL.COM',
    'kedubet@yahoo.ca',
    'she.len@sask-tel.net',
    'maintance@logviewlogistics.ca',
    'harnaamtrucktrailer@gmail.com',
    'dahliwal_11@ymail.com',
    'uniconimprove1@gmail.com',
    'harry@guruconnection.ca',
    'inder@allfrieghttransportltd.com',
    'jarryjfleet@telus.net',
    'aschhima2@gmail.com',
    'sukhminderdeol11@gmail.com',
    'gklair001@gmail.com',
    'northcostexcavationltd@gmail.com',
    'rpushor@shaw.ca',
    'yarcki@hotmail.com',
    'panhilfright@gmail.com',
    'gtkarhantrucking@gmail.com',
    'gtkrahantrucking@gmail.com',
    'accounting@translogicgroup.com',
    'info@weststartstransport.com',
    'nabeerl-a19@hotmail.com',
    'gillcherry@hotmail.com',
    'jag.mahal@hotmail.com',
    'info@dynamicdartworks.ca',
    'bajwajadeep49@gmail.com',
    'gksara096@gmail.com',
    'prashinderbrar@gmail.com',
    'swytchdelivery@gmail.com',
    'billing@orbitmotorcarrier.ca',
    'navtejhaddu84@gmail.com',
    'salaman@mirtransportltd.com',
    'ap@westvav.com',
    'rweimer@bigcountrydralling.com',
    'billing@giantlogisticinc.com',
    'fastandfaithfulllogisticsinc@gmail.com',
    'paandgtruclingltd@yahoo.ca',
    'sheroodliquorland@gmail.com',
    'servive@sonictrucksales.com',
    'paramenterprise@outlook.com',
    'samil@mdxinc.ca',
    'hioghwayruntrans@outlook.com',
    'antalltruckrepair@gmail.com',
    'iqbaltoor332@gmail.com',
    'faougirrh@gmail.com',
    'jassjande113@gmail.com',
    'binfraentltd@gmail.com',
    'lakhwviedadrah@gmail.com',
    'parts@calgaryheavytrucks.com',
    'psbhangu12@yahoo.com',
    'maintenance@rovercarrer.ca',
    'switchxinvoies@gmail.com',
    'ernestopers27@gmail.com',
    'belkotwoing@outlook.com',
    'REPAIR.5GUYS@GMAIL.COM',
    'hcicarrierslts@gmail.com',
    'southcitymachining@protonmale.com',
    'singhjadeep0167@gmail.com',
    'makhanlally88@gmail.com',
    'gillscologistics@gmail.com',
    'brightwaystransport@hotmail.com',
    'eliteabtrucking@gmail.com',
    'tractionabby@shaw.ca',
    'karen.crossland@dwforwarders.com',
    'SALES@EMPIRETRANSPORT.NET',
    'manpreetdhinds00045@gmail.com',
    'jairol668@gmail.com',
    'ravinderrehsi21@yhaoo.com',
    'dispatch@mogacarrier.ca',
    'amantoor@yahoo.com',
    'kyle61foley@hotmail.com',
    'almohamad111@yahoo.com',
    'tmortensen@bigcountrydralling.com',
    'veyessalasadvavdo@gmail.com',
    'johalprotrucking@gmail.com',
    'drice@hudytech.com',
    'billing@greatwestmenworth.com',
    'sidhu_sundeep22@yahoo.com',
    'hiway10tranportationltd@gmail.com',
    'bathaljagraj@gmail.com',
    'dispatch@bircarriers.ca',
    'davidguenther701@gmail.com',
    'numanzz@gmail.com',
    'jloewen1997@gmail.com',
    'sekhonamrital@yahoo.ca',
    'jagiprandhawa@hotmail.com',
    'jadamchuk@maximstrucktrailer.com',
    'bhinderdeol007@gmail.com',
    'kamal@skyforce.ca',
    'accounts@apcocranes.com',
    'h.khela@yahoo.com',
    'a.sarana@hotmail.com',
    'sparkytransport@shaw.ca',
    'bandbtruck@hotmail.com',
    'jermeys@rocklinbetransport.com',
    'trendlinelogistic@gmail.com',
    'gurnaamtranport@gmail.com',
    'info@hbsiteworks.ca',
    'brian@kansasrigetrucking.com',
    'leakyg@xtlornet.ca',
    'ggigarmahla@gmail.com',
    'marryarbeau313@hotmail.com',
    'invoice@supercattransport.com',
    'office@eldanielsimportinginc.com',
    'grewakbal24@yahoo.com',
    'heavysquardmechincal@hotmail.com',
    'makitcheema88@gmail.com',
    'ftaenterprises@shaw.ca',
    'goldrodgerlogistics@gmail.com',
    'parts@atitruckrepiar.ca',
    'deckxcarrier@gmail.com',
    'PARMJEETSINGHBAATH@YAHOO.COM',
    'paramjeetsinghbaath@yahoo.com',
    'info@sangherabrostranport.com',
    'bagrymukhtiar85@gmail.com',
]);
?>